# test_pln_rules.jl
# ─────────────────────────────────────────────────────────────────────────────
# The 2-premise rule tail beyond HMP: conjunction (eq 21) and disjunction (eq 24) forward
# maps + sensitivities, plus the negation forward map (§3.4), exercised through the
# rule-DISPATCHED supply / factor-demand-pair. Differentially validated against the Julia
# oracle (PLNDemand.jl):
#   forward (oracle :309-311): conj (0.56,0.985), disj (0.94,0.985), neg (0.3,0.85)
#   demand  (oracle demand_adjoint∘sens_*): conj (0.0875,0.15), disj (0.1,0.1)
# (Demand goldens generated by running sens_conjunction/sens_disjunction + demand_adjoint
#  on premises (0.8,0.9),(0.7,0.85) with d_v=1.0 — not hand-computed.)
#
# Also confirms the dispatch refactor is rule-generic: a conjunction factor and a disjunction
# factor over the SAME premises route to the correct forward map and sensitivity by their
# rule symbol — `supply`/`factor-demand-pair` are no longer HMP-hardcoded.

using Test
using MeTTaCore.Interpreter
using MeTTaCore.Interpreter.StandardMeTTa

@testset "PLN rules — conjunction/disjunction/negation (forward + demand via dispatch, vs oracle)" begin
    sp = Space()
    load_core_stdlib!(sp)
    load_metta!(sp, read(joinpath(@__DIR__, "..", "lib", "pln", "pln_factor_graph.metta"), String))

    load_metta!(sp, """
    (message P (stv 0.8 0.9))
    (message Q (stv 0.7 0.85))
    (factor cf conjunction (premises P Q) (conclusion Rc))
    (produces Rc cf)
    (factor df disjunction (premises P Q) (conclusion Rd))
    (produces Rd df)
    """)

    asserts = """
    !(assertEqual (fwd-conjunction (stv 0.8 0.9) (stv 0.7 0.85)) (stv 0.5599999999999999 0.985))
    !(assertEqual (fwd-disjunction (stv 0.8 0.9) (stv 0.7 0.85)) (stv 0.9400000000000001 0.985))
    !(assertEqual (fwd-negation (stv 0.7 0.85)) (stv 0.30000000000000004 0.85))
    !(assertEqual (supply Rc) (stv 0.5599999999999999 0.985))
    !(assertEqual (supply Rd) (stv 0.9400000000000001 0.985))
    !(assertEqual (factor-demand-pair Rc 1.0) (dpair 0.08749999999999997 0.15000000000000002))
    !(assertEqual (factor-demand-pair Rd 1.0) (dpair 0.09999999999999998 0.09999999999999998))
    """
    rs = load_metta!(sp, asserts)
    errs = filter(r -> r isa Expression && !isempty(r.children) && r.children[1] == Sym("Error"), rs)
    @test isempty(errs)
    @test length(rs) == 7
end
