#!/usr/bin/env bash
# extract_corpus.sh — turn UPSTREAM's XSB oracle corpus into a Julia-readable fixture.
#
# ─── WHAT THIS IS ────────────────────────────────────────────────────────────────────────────────
# `swipl-devel/tests/xsb/` ships ELEVEN test directories, 338 `*_old` gold-output files. The richest
# for us is `wfs_tests/`: each `pNN.P` begins with ONE machine-readable ground-truth fact —
#
#     query(p24, p, [p,q,r,s], [s], []).
#     %     name  goal  all-subgoals  TRUE-set  UNDEFINED-set
#
# Everything not in TrueSet or UndefSet is FALSE. That is a complete Well-Founded Semantics
# conformance table for 72 programs, written by the people who defined the semantics.
#
# 🔴 WHY THIS MATTERS MORE THAN ANOTHER HAND-WRITTEN TEST. Our `test_delays.jl` is mostly DNF
# ALGEBRA (dnf_and distributes, dnf_or dedups) plus a single end-to-end paradox. Algebra tests
# cannot see a wrong FIXPOINT. This corpus can: it states, per program, exactly which subgoals are
# true, which are undefined, and — by omission — which are false.
# `[[feedback_oracle_must_observe_the_defect_class]]`.
#
# ─── WHY swipl PARSES IT AND NOT A REGEX ─────────────────────────────────────────────────────────
# The goals are real Prolog terms — `win(_A)`, nested lists, module qualifiers. A regex gets `p06`
# right and `win(_A)` wrong, silently, which is the worst of both. `read_term/3` is exact, and we
# have the binary.
#
#   test/standard/tabling/upstream/extract_corpus.sh        # regenerate wfs_corpus.tsv
set -uo pipefail
UP="${SWIPL_DEVEL:-$HOME/dev-zone/swipl-devel}"
SRC="$UP/tests/xsb/wfs_tests"
OUT="$(cd "$(dirname "$0")" && pwd)/wfs_corpus.tsv"

command -v swipl >/dev/null || { echo "swipl not on PATH"; exit 2; }
[ -d "$SRC" ] || { echo "no corpus at $SRC (set SWIPL_DEVEL)"; exit 2; }

{
  printf '# GENERATED by extract_corpus.sh from swipl-devel/tests/xsb/wfs_tests — DO NOT HAND-EDIT.\n'
  printf '# name\tgoal\tsubgoals\ttrue_set\tundef_set\n'
  for f in "$SRC"/*.P; do
    swipl -q -g "
      catch(( open('$f', read, S),
              read_term(S, T, [variable_names(_)]),
              close(S),
              ( T = query(N,G,SG,TS,US)
              -> format('~q\t~q\t~q\t~q\t~q~n', [N,G,SG,TS,US])
              ;  true )
            ), _, true)" -t halt 2>/dev/null
  done
} > "$OUT"
n=$(grep -vc '^#' "$OUT")
echo "  wrote $OUT — $n programs"
