#!/usr/bin/env bash
# translate_corpus.sh — emit wfs_programs.tsv: every XSB wfs_tests program this translator can
# handle, in MeTTa, with its gold sets in the same notation.
#
# 🔴 REFUSALS ARE RECORDED, NOT DROPPED. A program the translator cannot handle appears as a
# `# REFUSED` line with its reason. Silently emitting 57 rows for a 72-program corpus and calling it
# "the corpus" is how coverage gets overstated — the count you can quote must be the count that ran.
set -uo pipefail
UP="${SWIPL_DEVEL:-$HOME/dev-zone/swipl-devel}"
SRC="$UP/tests/xsb/wfs_tests"
HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/wfs_programs.tsv"
command -v swipl >/dev/null || { echo "swipl not on PATH"; exit 2; }

{
  printf '# GENERATED by translate_corpus.sh — DO NOT HAND-EDIT.\n'
  printf '# name\ttabled\tprogram\tgoals\ttrue_set\tundef_set\n'
  for f in "$SRC"/p*.P; do
    b=$(basename "$f" .P)
    out=$(cd "$SRC" && timeout 30 swipl -q "$HERE/translate_corpus.pl" "$f" 2>/dev/null | head -1)
    case "$out" in
      OK*)      printf '%s\t%s\n' "$b" "${out#OK	}" ;;
      REFUSED*) printf '# REFUSED %s\t%s\n' "$b" "${out#REFUSED	}" ;;
      *)        printf '# ERROR %s\n' "$b" ;;
    esac
  done
} > "$OUT"
ok=$(grep -vc '^#' "$OUT"); ref=$(grep -c '^# REFUSED' "$OUT")
echo "  wrote $OUT — $ok translated, $ref refused"
