#!/usr/bin/env bash
# translate_delay_corpus.sh — emit delay_programs.tsv: every XSB delay_tests program this translator
# can handle, in MeTTa, with its gold truth-values in the same notation.
#
# ─── WHY delay_tests, WHEN wfs_tests IS ALREADY WIRED ────────────────────────────────────────────
# Our own `test_delays.jl` is mostly DNF ALGEBRA — `dnf_and` distributes, `dnf_or` dedups — plus one
# end-to-end paradox. `upstream/README.md` says it outright: "Algebra assertions cannot see a wrong
# FIXPOINT." These programs can: each is a dynamically-stratified or delay-requiring program whose
# whole point is which literals end up true/false/undefined AFTER delay and simplification.
#
# ─── WHY THE GOLD IS PARSED FROM `*_old`, AND WHY THAT IS THE RISKY PART ─────────────────────────
# wfs_tests ships a machine-readable `query(name, goal, subgoals, TRUE, UNDEF)` fact, so
# translate_corpus.pl emits program and gold from ONE pass over ONE file. delay_tests does not: the
# expectation is upstream's recorded STDOUT in `<name>_old`, e.g.
#     p. s is true (OK)
#     q is false (OK)
# So gold lives in a second file, which is exactly the drift risk translate_corpus.pl warns about
# ("Emitting them separately is how a program and its expectation drift apart"). This script keeps
# the one-pass property at the ROW level instead: one program is read, its gold is read, and BOTH are
# written into a single row or the program is refused. A row can never carry another row's gold.
#
# ─── WHAT IT REFUSES, AND WHY EACH REFUSAL IS A REAL DISTINCTION ─────────────────────────────────
#   residual-output    gold contains `(und :- [[tnot und]])` — get_residual/2 prints the RESIDUAL
#                      PROGRAM, not truth values. A different oracle; do not coerce it into one.
#   delay-list-output  gold contains clauses like `p(3,[a],A) :- tnot p(3,[a],3).` — conditional
#                      ANSWERS with delay lists. Same reason.
#   prose-output       gold is commentary ("t: gets a conditional answer from its first clause").
#   conflicting-gold   the same subgoal is printed both true and false under different test contexts
#                      (`test_p` vs `test_s`). That is not a translation failure, it is a program
#                      whose expectation is context-dependent, and a single truth-set cannot hold it.
#   <translator>       whatever translate_corpus.pl itself refuses, passed through verbatim.
#
# ⚠️ EXPECTED DIFFERENCES ARE NOT REFUSALS. Upstream's own `xsb_test_delay.pl` pre-labels which
# programs need the §7.6.1 simplification we deliberately did not build ("Needs n simplification",
# "Needs p+n simplification", "Needs cascading simplifications"). Those are translated and emitted
# with a `needs_simplification` flag so the Julia side can assert them as CLASSIFIED differences
# rather than silently passing or silently failing. `gfp` needs simplification to CASCADE, which is
# worth knowing before writing §7.6.1 rather than after.
set -uo pipefail
UP="${SWIPL_DEVEL:-$HOME/dev-zone/swipl-devel}"
SRC="$UP/tests/xsb/delay_tests"
HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/delay_programs.tsv"
LABELS="$SRC/xsb_test_delay.pl"
command -v swipl >/dev/null || { echo "swipl not on PATH"; exit 2; }
[ -d "$SRC" ] || { echo "no delay_tests at $SRC"; exit 2; }

export SRC LABELS
python3 - "$HERE" > "$OUT" <<'PY'
import os, re, subprocess, sys, glob
HERE = sys.argv[1]; SRC = os.environ["SRC"]; LABELS = os.environ["LABELS"]

# upstream's own labelling: `xsb_test(dynstrat1).   % Needs n simplification`
needs = {}
for line in open(LABELS, errors="replace"):
    m = re.match(r'\s*xsb_test\((\w+)\)\.\s*%\s*(.*?)\s*$', line)
    # ⚠️ MUST test "Needs", not "simplification" — upstream writes BOTH "Needs n simplification"
    # AND "No simplification" as labels, and a substring test flags the second as if it were the
    # first. Caught before this reached the Julia side, where it would have asserted the WRONG
    # classification for 6 programs (dynstrat2, nonstrat1, p1-p4) that need no simplification at all.
    if m and m.group(2).lower().startswith("needs"):
        needs[m.group(1)] = m.group(2)

TRUTH  = re.compile(r'^(?:([a-z]\w*)\.\s+)?([a-z]\w*(?:\([^()]*\))?)\s+is\s+(true|false|undefined)\b', re.I)
CLAUSE = re.compile(r'^\(?[a-z]\w*(\([^)]*\))?\s*:-')      # residual program / delay-list output

def render(goal: str) -> str:
    """Render a gold subgoal exactly as translate_corpus.pl renders a call: p -> (p), i(r) -> (i r)."""
    m = re.match(r'^([a-z]\w*)\(([^()]*)\)$', goal)
    if m:
        args = [a.strip() for a in m.group(2).split(",") if a.strip()]
        return "(" + " ".join([m.group(1)] + args) + ")"
    return f"({goal})"

print("# GENERATED by translate_delay_corpus.sh — DO NOT HAND-EDIT.")
print("# name\ttabled\tprogram\ttrue_set\tfalse_set\tundef_set\tneeds_simplification")
n_ok = n_ref = 0
for p in sorted(glob.glob(os.path.join(SRC, "*.P"))):
    name = os.path.basename(p)[:-2]
    gold = os.path.join(SRC, name + "_old")
    if not os.path.exists(gold):
        print(f"# REFUSED {name}\tno gold (_old) file"); n_ref += 1; continue

    lines = [l.strip() for l in open(gold, errors="replace") if l.strip()]
    if any(CLAUSE.match(l) for l in lines):
        print(f"# REFUSED {name}\tresidual/delay-list output — a different oracle kind"); n_ref += 1; continue

    tv, conflict, unparsed = {}, None, None
    for l in lines:
        m = TRUTH.match(l)
        if not m:
            unparsed = l[:60]; break
        _, sub, val = m.group(1), m.group(2), m.group(3).lower()
        if sub in tv and tv[sub] != val:
            conflict = f"{sub}: {tv[sub]} vs {val}"; break
        tv[sub] = val
    if unparsed is not None:
        print(f"# REFUSED {name}\tnon-truth-value gold line: {unparsed}"); n_ref += 1; continue
    if conflict:
        print(f"# REFUSED {name}\tconflicting gold across test contexts ({conflict})"); n_ref += 1; continue
    if not tv:
        print(f"# REFUSED {name}\tempty gold"); n_ref += 1; continue

    # translate the PROGRAM with the existing, reviewed translator — do not write a second one
    try:
        r = subprocess.run(["swipl", "-q", os.path.join(HERE, "translate_corpus.pl"), p],
                           cwd=SRC, capture_output=True, text=True, timeout=30)
        out = (r.stdout or "").splitlines()[0] if r.stdout.strip() else ""
    except Exception as e:
        print(f"# REFUSED {name}\ttranslator error: {type(e).__name__}"); n_ref += 1; continue
    if out.startswith("REFUSED"):
        print(f"# REFUSED {name}\t{out.split(chr(9),1)[1] if chr(9) in out else 'translator refused'}")
        n_ref += 1; continue
    if not out.startswith("OK"):
        print(f"# REFUSED {name}\ttranslator produced no OK row"); n_ref += 1; continue

    f = out.split("\t")            # OK, tabled, program, goals, true, undef  (last three empty here)
    tabled, program = f[1], f[2]
    T = ",".join(render(k) for k, v in tv.items() if v == "true")
    F = ",".join(render(k) for k, v in tv.items() if v == "false")
    U = ",".join(render(k) for k, v in tv.items() if v == "undefined")
    print(f"{name}\t{tabled}\t{program}\t{T}\t{F}\t{U}\t{needs.get(name,'')}")
    n_ok += 1
print(f"# SUMMARY translated={n_ok} refused={n_ref}", file=sys.stderr)
PY
ok=$(grep -vc '^#' "$OUT"); ref=$(grep -c '^# REFUSED' "$OUT")
simp=$(awk -F'\t' '!/^#/ && $7!=""' "$OUT" | wc -l)
echo "  wrote $OUT — $ok translated ($simp need §7.6.1 simplification), $ref refused"
