# test_pln_rows.jl
# ─────────────────────────────────────────────────────────────────────────────
# Rows-only rule tail: inversion (3-premise) demand + the negation (1-premise) demand,
# plus the inversion/deduction forward maps. Differentially validated vs the Julia oracle
# (PLNDemand.jl), goldens GENERATED by running fwd_*/sens_*/demand_adjoint:
#   forward: inversion (0.61875,0.612), deduction (0.501667,0.4624)
#   demand:  inversion (0.0625,0.15,0.12364), negation 0.15
#
# ADVERSARIAL SINGULARITY (the rows-only failure mode): inversion's sens_A = sBA·sB/sA² blows
# up as sA→0 and is CAPPED at SENS_CAP. The cap is NOT cosmetic — it changes the NORMALIZER S,
# hence the OTHER premises' demand. At sA=0.0001 the oracle gives (0.1, 0.001485, 0.001): the
# singular premise A absorbs the demand (0.1), the others get the cap-scaled remainder. An
# implementation that drops the cap (or returns 0/∞ at the singularity) produces different
# Ψ_B/Ψ_BA, so this exact-value assert fails without a correct cap.

using Test
using MeTTaCore.Eval
using MeTTaCore.StandardMeTTa

@testset "PLN rows-only — inversion (3-premise + singularity cap) + negation demand vs oracle" begin
    sp = Space()
    load_core_stdlib!(sp)
    load_metta!(sp, read(joinpath(@__DIR__, "..", "..", "lib", "pln", "pln_factor_graph.metta"), String))

    load_metta!(sp, """
    (message Ai (stv 0.8 0.9))
    (message Bi (stv 0.5 0.85))
    (message BAi (stv 0.99 0.80))
    (factor invf inversion (premises Ai Bi BAi) (conclusion ABc))
    (produces ABc invf)
    (message As (stv 0.0001 0.9))
    (factor invs inversion (premises As Bi BAi) (conclusion ABs))
    (produces ABs invs)
    (message X (stv 0.7 0.85))
    (factor negf negation (premises X) (conclusion NX))
    (produces NX negf)
    """)

    asserts = """
    !(assertEqual (fwd-inversion (stv 0.8 0.9) (stv 0.5 0.85) (stv 0.99 0.80)) (stv 0.6187499999999999 0.6120000000000001))
    !(assertEqual (fwd-deduction (stv 0.4 0.8) (stv 0.6 0.85) (stv 0.99 0.80) (stv 0.5 0.85)) (stv 0.5016666666666667 0.46240000000000003))
    !(assertEqual (factor-demand-triple ABc 1.0) (dtriple 0.062499999999999986 0.15000000000000002 0.12363636363636363))
    !(assertEqual (factor-demand-triple ABs 1.0) (dtriple 0.09999999999999998 0.0014850000000000004 0.0009999999999999998))
    !(assertEqual (factor-demand-single NX 1.0) (dsingle 0.15000000000000002))
    """
    rs = load_metta!(sp, asserts)
    errs = filter(r -> r isa Expression && !isempty(r.children) && r.children[1] == Sym("Error"), rs)
    @test isempty(errs)
    @test length(rs) == 5
end
